apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false #don't push to docker hub
  artifacts: # all the things built
    - image: tjanssen33/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: # how to handle any files that change inside here
        manual:
          - src: 'src/**/*.ts'
            dest: . # where to sync the file to
